services:
  postgres:
    image: postgres:11.7-alpine
    container_name: ecommerce-postgres-db
    ports:
      - 5012:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
